apiVersion: v1
kind: Namespace
metadata:
  name: app-test-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front-deploy
  namespace: app-test-1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: app-front
  template:
    metadata:
      labels:
        app: app-front
    spec:
      containers:
      - name: app-front
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-front-svc
  namespace: app-test-1
  labels:
    app: app-front
spec:
  type: NodePort
  ports:
  - name:  http
    port:  80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: app-front
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-front-ingress
  namespace: app-front
spec:
  rules:
  - host: "app-front.my.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-front-svc 
            port:
              number: 80
  tls:
  - hosts:
    - app-front.my.org
    secretName: app-front-tls-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-front-cert
  namespace: app-test-1
spec:
  secretName: app-front-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - app-front.my.org
