apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deploy
  namespace: app-test-1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: mailhog/mailhog
        ports:
        - name: web
          containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
  namespace: app-test-1
  labels:
    app: notification-service
spec:
  type: NodePort
  ports:
  - name:  http
    port:  8025
    targetPort: 8025
    nodePort: 30085
    protocol: TCP
  selector:
    app: notification-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-service-ingress
  namespace: app-test-1
spec:
  rules:
  - host: "notification-service.my.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notification-service-svc 
            port:
              number: 8025
  tls:
  - hosts:
    - notification-service.my.org
    secretName: notification-service-tls-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notification-service-cert
  namespace: app-test-1
spec:
  secretName: notification-service-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - notification-service.my.org
