apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
  namespace: app-test-1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: rabbitmq
        ports:
        - name: web
          containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
  namespace: app-test-1
  labels:
    app: order-service
spec:
  type: NodePort
  ports:
  - name:  http
    port:  5672
    targetPort: 5672
    nodePort: 30083
    protocol: TCP
  selector:
    app: order-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-service-ingress
  namespace: app-test-1
spec:
  rules:
  - host: "order-service.<your-domain>"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: order-service-svc 
            port:
              number: 5672
  tls:
  - hosts:
    - order-service.<your-domain>
    secretName: <ssl-secret>              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: order-service-cert
  namespace: app-test-1
spec:
  secretName: order-service-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - order-service.<your-domain>
