apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deploy
  namespace: app-test-1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: redis
        ports:
        - name: web
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
  namespace: app-test-1
  labels:
    app: payment-service
spec:
  type: NodePort
  ports:
  - name:  http
    port:  6379
    targetPort: 6379
    nodePort: 30084
    protocol: TCP
  selector:
    app: payment-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-service-ingress
  namespace: app-test-1
spec:
  rules:
  - host: "payment-service.my.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payment-service-svc 
            port:
              number: 6379
  tls:
  - hosts:
    - payment-service.my.org
    secretName: payment-service-tls-secret             
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: payment-service-cert
  namespace: app-test-1
spec:
  secretName: payment-service-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - payment-service.my.org
