apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deploy
  namespace: app-test-1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: mongo
        ports:
        - name: web
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
  namespace: app-test-1
  labels:
    app: product-service
spec:
  type: NodePort
  ports:
  - name:  http
    port:  27017
    targetPort: 27017
    nodePort: 30082
    protocol: TCP
  selector:
    app: product-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-service-ingress
  namespace: app-test-1
spec:
  rules:
  - host: "product-service.<your-domain>"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: product-service-svc 
            port:
              number: 27017
  tls:
  - hosts:
    - product-service.<your-domain>
    secretName: <ssl-secret>              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: product-service-cert
  namespace: app-test-1
spec:
  secretName: product-service-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - product-service.<your-domain>
