apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service-deploy
  namespace: app-test-1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: elasticsearch
        ports:
        - name: web
          containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: review-service-svc
  namespace: app-test-1
  labels:
    app: review-service
spec:
  type: NodePort
  ports:
  - name:  http
    port:  9200
    targetPort: 9200
    nodePort: 30086
    protocol: TCP
  selector:
    app: review-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: review-service-ingress
  namespace: app-test-1
spec:
  rules:
  - host: "review-service.my.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: review-service-svc 
            port:
              number: 9200
  tls:
  - hosts:
    - review-service.my.org
    secretName: review-service-tls-secret           
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: review-service-cert
  namespace: app-test-1
spec:
  secretName: review-service-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - review-service.my.org
