apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deploy
  namespace: app-test-1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: jhipster/jhipster-registry
        ports:
        - name: web
          containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  namespace: app-test-1
  labels:
    app: user-service
spec:
  type: NodePort
  ports:
  - name:  http
    port:  8761
    targetPort: 8761
    nodePort: 30081
    protocol: TCP
  selector:
    app: user-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-ingress
  namespace: app-test-1
spec:
  rules:
  - host: "user-service.my.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-service-svc 
            port:
              number: 8761
  tls:
  - hosts:
    - user-service.my.org
    secretName: user-service-tls-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: user-service-cert
  namespace: app-test-1
spec:
  secretName: user-service-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - user-service.my.org
